apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: lektion11-search-movies
  ports:
    - appProtocol: http
      protocol: TCP
      port: 8080
      targetPort: 8080

